### ISSUE TITLE
[FEATURE] port management (port-forwarding)

### ISSUE THREAD

**Issue by blckbx** [Mawthuq-Software/wireguard-manager-and-api#13]
**Is your feature request related to a problem? Please describe.**
Offering VPN support for a special case where all of our clients need an exposed (forwarded) port for incoming traffic, it would be very handy and comfortable for us if wg manager had the opportunity to add/remove/edit/store forwarded ports as well.

**Describe the solution you'd like**
A way to request / delete / edit a forwarded port the same way a peer is added / removed / edited on wireguard instances. On adding a peer the port should be reported back via API to be added to the peer's auto-configured wiregard.conf file. 

**Describe alternatives you've considered**
Guess we need to do it manually. I don't know any other solution to automatically manage this. Open and grateful for any hints on this topic.

**Comment by RaspberryTech01** [comment]
I am assuming your clients have a firewall which doesn't allow incoming and outgoing without explicit rules (whereas normally its just outgoing). The issue is that this is not really something that users of this project really need. It can even be a security risk as the server should barely keep any user info as possible.

That being said, if you know some programming you could fork the project and setup your own edits. It wouldn't be too hard either. Just need to find the route and follow the functions down the path into where its added to the database. One other solution if you are not comfortable programming in go is setup your own sub API server which records this data before passing the request onward.

I still dont quite understand why you would need to store the client's port forwarded port on the server? Generally speaking its not about port forwarding on clients, only on the server. How normal firewalls work is they allow outgoing requests and any responses are allowed in.

**Comment by blckbx** [comment]
Thanks for the pointers! 
The reason why we need to store it is that ports have to be unique for every peer to be able to connect to each other. I'll give this sub-API a go. Thanks for reaching out!
